export enum UserRole {
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
  LOAN_OFFICER = "LOAN_OFFICER",
  REVIEWER = "REVIEWER",
}

export enum ApplicationStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  PENDING_DOCUMENTS = "PENDING_DOCUMENTS",
  DOCUMENT_VERIFICATION = "DOCUMENT_VERIFICATION",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  DISBURSED = "DISBURSED",
  CLOSED = "CLOSED",
}

export enum LoanType {
  PERSONAL = "PERSONAL",
  MORTGAGE = "MORTGAGE",
  AUTO = "AUTO",
  BUSINESS = "BUSINESS",
  DEBT_CONSOLIDATION = "DEBT_CONSOLIDATION",
  OTHER = "OTHER",
}

export enum UrgencyLevel {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum MaritalStatus {
  SINGLE = "SINGLE",
  MARRIED = "MARRIED",
  DIVORCED = "DIVORCED",
  WIDOWED = "WIDOWED",
  SEPARATED = "SEPARATED",
}

export enum HousingStatus {
  OWNER = "OWNER",
  RENTER = "RENTER",
  FAMILY = "FAMILY",
  OTHER = "OTHER",
}

export enum EmploymentStatus {
  EMPLOYED = "EMPLOYED",
  SELF_EMPLOYED = "SELF_EMPLOYED",
  UNEMPLOYED = "UNEMPLOYED",
  RETIRED = "RETIRED",
  STUDENT = "STUDENT",
}

export enum ContractType {
  PERMANENT = "PERMANENT",
  FIXED_TERM = "FIXED_TERM",
  PART_TIME = "PART_TIME",
  FREELANCE = "FREELANCE",
  OTHER = "OTHER",
}

export enum DocumentCategory {
  ID_CARD = "ID_CARD",
  PASSPORT = "PASSPORT",
  DRIVER_LICENSE = "DRIVER_LICENSE",
  INCOME_PROOF = "INCOME_PROOF",
  PAYSLIP = "PAYSLIP",
  BANK_STATEMENT = "BANK_STATEMENT",
  TAX_DOCUMENT = "TAX_DOCUMENT",
  RESIDENCE_PROOF = "RESIDENCE_PROOF",
  GUARANTOR_ID = "GUARANTOR_ID",
  GUARANTOR_INCOME = "GUARANTOR_INCOME",
  COLLATERAL_DOC = "COLLATERAL_DOC",
  OTHER = "OTHER",
}

export enum DocumentStatus {
  PENDING = "PENDING",
  RECEIVED = "RECEIVED",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
}

export enum CollateralType {
  REAL_ESTATE = "REAL_ESTATE",
  VEHICLE = "VEHICLE",
  JEWELRY = "JEWELRY",
  SAVINGS = "SAVINGS",
  OTHER = "OTHER",
}

export enum NotificationType {
  STATUS_CHANGE = "STATUS_CHANGE",
  DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED",
  DOCUMENT_MISSING = "DOCUMENT_MISSING",
  GOOGLE_DOC_UPDATED = "GOOGLE_DOC_UPDATED",
  CASE_ASSIGNED = "CASE_ASSIGNED",
  NOTE_ADDED = "NOTE_ADDED",
  GENERAL = "GENERAL",
}
